# Generated by Django 3.1.5 on 2021-03-07 08:11

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('S', 'Продавец'), ('C', 'Покупатель')], db_index=True, max_length=1, null=True, verbose_name='Роль')),
                ('num_failed_logins', models.IntegerField(null=True, verbose_name='Количество неудачных входов')),
                ('photo', models.ImageField(null=True, upload_to='users/', verbose_name='Фото профиля')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Телефон')),
                ('birthday', models.DateField(blank=True, db_index=True, null=True, verbose_name='День рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], db_index=True, default='M', max_length=1, null=True, verbose_name='Пол')),
                ('country', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование товара')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7, verbose_name='Стоимость товара')),
                ('description', models.TextField(max_length=500, verbose_name='Описание товара')),
                ('brand', models.CharField(db_index=True, max_length=150, verbose_name='Брэнд')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('issue_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата изготовления')),
                ('vendor_code', models.CharField(db_index=True, max_length=254, null=True, verbose_name='Артикул товара')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата опубликования')),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, size=None, verbose_name='Тэги')),
                ('rating', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Рэйтинг товара')),
                ('counter', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование тэга')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ecomm.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписчик')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=150, null=True, verbose_name='Название компании')),
                ('legal_entity', models.CharField(db_index=True, max_length=150, null=True, verbose_name='Юридическое лицо')),
                ('manufacturer', models.CharField(db_index=True, max_length=150, null=True, verbose_name='Производитель')),
                ('manufacturer_country', models.CharField(db_index=True, max_length=150, null=True, verbose_name='Страна происхождения')),
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='ecomm.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('good', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecomm.good', verbose_name='Товар')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecomm.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 1')),
                ('image_2', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 2')),
                ('image_3', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 3')),
                ('image_4', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 4')),
                ('image_5', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 5')),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecomm.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ecomm.seller', verbose_name='Продавец'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True, verbose_name='Дата покупки')),
                ('customuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ecomm.customuser', verbose_name='Пользователь')),
                ('goods', models.ManyToManyField(blank=True, related_name='customers', to='ecomm.Good', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=100, null=True)),
                ('size', models.IntegerField(null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='ecomm.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
