# Generated by Django 3.1.5 on 2021-01-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.category')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.category')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('description', models.TextField(max_length=500)),
                ('rating', models.PositiveIntegerField(db_index=True)),
                ('brand', models.CharField(db_index=True, max_length=150)),
                ('is_available', models.BooleanField(db_index=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='goods', to='ecomm.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('age', models.IntegerField(db_index=True)),
                ('country', models.CharField(db_index=True, max_length=150)),
                ('city', models.CharField(db_index=True, max_length=150)),
                ('address', models.CharField(db_index=True, max_length=150)),
                ('goods', models.ManyToManyField(blank=True, related_name='customers', to='ecomm.Good')),
            ],
        ),
    ]
