# Generated by Django 3.1.5 on 2021-01-26 12:07

from django.db import migrations, models


def shipping(apps, schema_editor):
    Good = apps.get_model('ecomm', 'Good')
    for good in Good.objects.all():
        good.shipping_charge = round((good.price * 20) / 100, 2)
        good.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Good',
            name='shipping_charge',
            field=models.DecimalField(default=0, max_digits=7, decimal_places=2, db_index=True)
        ),
        migrations.RunPython(shipping, reverse_code=migrations.RunPython.noop),
    ]
