# Generated by Django 3.1.5 on 2021-02-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_good_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='good',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='good',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='good',
            name='description',
        ),
        migrations.RemoveField(
            model_name='good',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='good',
            name='name',
        ),
        migrations.RemoveField(
            model_name='good',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='good',
            name='shipping_charge',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
