# Generated by Django 3.1.5 on 2021-02-01 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_auto_20210201_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='default title', max_length=150, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('color', models.CharField(db_index=True, default='default color', max_length=100)),
                ('size', models.IntegerField(default='')),
                ('length', models.DecimalField(decimal_places=2, default='', max_digits=7)),
                ('width', models.DecimalField(decimal_places=2, default='', max_digits=7)),
                ('height', models.DecimalField(decimal_places=2, default='', max_digits=7)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='characteristics', serialize=False, to='ecomm.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_1', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 1')),
                ('image_2', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 2')),
                ('image_3', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 3')),
                ('image_4', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 4')),
                ('image_5', models.ImageField(null=True, upload_to='goods_images/', verbose_name='Фото 5')),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='images', serialize=False, to='ecomm.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('first_name', models.CharField(db_index=True, max_length=150, verbose_name='Имя (по паспорту)')),
                ('last_name', models.CharField(db_index=True, max_length=150, verbose_name='Фамилия (по паспорту)')),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата регистрация')),
                ('role', models.CharField(blank=True, choices=[('S', 'Продавец'), ('C', 'Покупатель')], db_index=True, max_length=1, verbose_name='Роль')),
                ('last_visit_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Последний визит')),
                ('active', models.BooleanField(db_index=True, verbose_name='Активный')),
                ('personal', models.BooleanField(db_index=True, default=False, verbose_name='Статус персонала')),
                ('num_failed_logins', models.IntegerField(default=0, verbose_name='Количество неудачных входов')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='good',
            name='brand',
            field=models.CharField(db_index=True, default='default brand', max_length=150, verbose_name='Брэнд'),
        ),
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(default='default description', max_length=500, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Наличие товара'),
        ),
        migrations.AddField(
            model_name='good',
            name='issue_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2021, 1, 1), verbose_name='Дата изготовления'),
        ),
        migrations.AddField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата опубликования'),
        ),
        migrations.AddField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Рэйтинг товара'),
        ),
        migrations.AddField(
            model_name='good',
            name='shipping_charge',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='good',
            name='title',
            field=models.CharField(db_index=True, default='default title', max_length=150, verbose_name='Наименование товара'),
        ),
        migrations.AddField(
            model_name='good',
            name='vendor_code',
            field=models.CharField(db_index=True, default='', max_length=254, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=10, max_digits=7, verbose_name='Стоимость товара'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='default title', max_length=150, verbose_name='Наименование тэга')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ecomm.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('photo', models.ImageField(null=True, upload_to='sellers/', verbose_name='Фото профиля')),
                ('phone', models.CharField(default='default phone', max_length=150, unique=True, verbose_name='Телефон')),
                ('company_name', models.CharField(db_index=True, default='default name', max_length=150, verbose_name='Название компании')),
                ('legal_entity', models.CharField(db_index=True, default='default legal entity', max_length=150, verbose_name='Юридическое лицо')),
                ('country', models.CharField(db_index=True, default='', max_length=150, verbose_name='Страна')),
                ('city', models.CharField(db_index=True, default='', max_length=150, verbose_name='Город')),
                ('address', models.CharField(db_index=True, default='', max_length=150, verbose_name='Адрес')),
                ('manufacturer', models.CharField(db_index=True, default='', max_length=150, verbose_name='Производитель')),
                ('manufacturer_country', models.CharField(db_index=True, default='', max_length=150, verbose_name='Страна происхождения')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to='ecomm.user', verbose_name='Пользователь')),
                ('goods', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='ecomm.good', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('text', models.TextField(max_length=500)),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reviews', serialize=False, to='ecomm.user', verbose_name='Пользователь')),
                ('good', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ecomm.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('photo', models.ImageField(null=True, upload_to='customers/', verbose_name='Фото профиля')),
                ('phone', models.CharField(max_length=150, unique=True, verbose_name='Телефон')),
                ('birthday', models.DateField(blank=True, db_index=True, default=datetime.date(1970, 1, 1), verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], db_index=True, default='M', max_length=1, verbose_name='Пол')),
                ('country', models.CharField(db_index=True, default='', max_length=150, verbose_name='Страна')),
                ('city', models.CharField(db_index=True, default='', max_length=150, verbose_name='Город')),
                ('address', models.CharField(db_index=True, default='', max_length=150, verbose_name='Адрес')),
                ('purchase_date', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата покупки')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to='ecomm.user', verbose_name='Пользователь')),
                ('goods', models.ManyToManyField(blank=True, related_name='customers', to='ecomm.Good', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
