# Generated by Django 3.1.5 on 2021-02-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_auto_20210201_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='good',
            name='shipping_charge',
        ),
        migrations.AddField(
            model_name='good',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ecomm.tag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='height',
            field=models.DecimalField(decimal_places=2, default='default height', max_digits=7),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='length',
            field=models.DecimalField(decimal_places=2, default='default length', max_digits=7),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='size',
            field=models.IntegerField(default='default size'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='width',
            field=models.DecimalField(decimal_places=2, default='default width', max_digits=7),
        ),
        migrations.AlterField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата опубликования'),
        ),
        migrations.AlterField(
            model_name='good',
            name='vendor_code',
            field=models.CharField(db_index=True, default='default vendor code', max_length=254, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последний визит'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрация'),
        ),
    ]
