# Generated by Django 3.1.5 on 2021-02-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_auto_20210201_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(db_index=True, default='default nickname', max_length=150, verbose_name='Ник'),
        ),
    ]
