# Generated by Django 3.1.5 on 2021-02-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_auto_20210202_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='goods',
        ),
        migrations.AddField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ecomm.seller', verbose_name='Продавец'),
        ),
    ]
