# Generated by Django 3.1.5 on 2021-02-06 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomm', '0007_auto_20210202_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='country',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='photo',
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('S', 'Продавец'), ('C', 'Покупатель')], db_index=True, max_length=1, verbose_name='Роль')),
                ('num_failed_logins', models.IntegerField(default=0, verbose_name='Количество неудачных входов')),
                ('photo', models.ImageField(null=True, upload_to='users/', verbose_name='Фото профиля')),
                ('phone', models.CharField(max_length=150, unique=True, verbose_name='Телефон')),
                ('birthday', models.DateField(blank=True, db_index=True, default=datetime.date(1970, 1, 1), verbose_name='День рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], db_index=True, default='M', max_length=1, verbose_name='Пол')),
                ('country', models.CharField(db_index=True, default='', max_length=150, verbose_name='Страна')),
                ('city', models.CharField(db_index=True, default='', max_length=150, verbose_name='Город')),
                ('address', models.CharField(db_index=True, default='', max_length=150, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to='ecomm.customuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reviews', serialize=False, to='ecomm.customuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to='ecomm.customuser', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
