# Generated by Django 3.1.5 on 2021-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_auto_20210206_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], db_index=True, default='M', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='num_failed_logins',
            field=models.IntegerField(null=True, verbose_name='Количество неудачных входов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('S', 'Продавец'), ('C', 'Покупатель')], db_index=True, max_length=1, null=True, verbose_name='Роль'),
        ),
    ]
