# Generated by Django 3.1.5 on 2021-02-06 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0009_auto_20210206_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='height',
            field=models.DecimalField(decimal_places=2, default='default height', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='length',
            field=models.DecimalField(decimal_places=2, default='default length', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='size',
            field=models.IntegerField(default='default size', null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='width',
            field=models.DecimalField(decimal_places=2, default='default width', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='good',
            name='issue_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата изготовления'),
        ),
        migrations.AlterField(
            model_name='good',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата опубликования'),
        ),
        migrations.AlterField(
            model_name='good',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Рэйтинг товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='vendor_code',
            field=models.CharField(db_index=True, max_length=254, null=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='legal_entity',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='manufacturer',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='manufacturer_country',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Страна происхождения'),
        ),
    ]
