# Generated by Django 3.1.5 on 2021-02-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_auto_20210206_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='color',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to='ecomm.customuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='good',
            name='brand',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=7, verbose_name='Стоимость товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='good',
            name='rating',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Рэйтинг товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ecomm.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='good',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='ecomm.tag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='good',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_name',
            field=models.CharField(db_index=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seller', serialize=False, to='ecomm.customuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Наименование тэга'),
        ),
    ]
