# Generated by Django 3.1.5 on 2021-02-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_auto_20210213_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('is_subscribed', models.BooleanField(default=False, verbose_name='Подписчик')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customuser', serialize=False, to='ecomm.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
