# Generated by Django 3.1.5 on 2021-02-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('ecomm', '0015_auto_20210223_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customuser',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='customuser',
        ),
    ]
